import typing

class Error(Exception): ...
class SchemaError(Error): ...

class Invalid(Error):
    path: typing.List[str]
    error_message: str
    error_type: str
    def __init__(self, message, path: typing.List[str] | None = None, error_message: str | None = None, error_type: str | None = None) -> None: ...
    @property
    def msg(self): ...
    def prepend(self, path) -> None: ...

class MultipleInvalid(Invalid):
    errors: typing.List[Error]
    def __init__(self, errors: typing.List[Error] | None = None) -> None: ...
    @property
    def msg(self) -> str: ...
    @property
    def path(self) -> typing.List[str]: ...
    @property
    def error_message(self) -> str: ...
    def add(self, error: Error) -> None: ...
    def prepend(self, path: typing.List[str]) -> None: ...

class RequiredFieldInvalid(Invalid): ...
class ObjectInvalid(Invalid): ...
class DictInvalid(Invalid): ...
class ExclusiveInvalid(Invalid): ...
class InclusiveInvalid(Invalid): ...
class SequenceTypeInvalid(Invalid): ...
class TypeInvalid(Invalid): ...
class ValueInvalid(Invalid): ...
class ContainsInvalid(Invalid): ...
class ScalarInvalid(Invalid): ...
class CoerceInvalid(Invalid): ...
class AnyInvalid(Invalid): ...
class AllInvalid(Invalid): ...
class MatchInvalid(Invalid): ...
class RangeInvalid(Invalid): ...
class TrueInvalid(Invalid): ...
class FalseInvalid(Invalid): ...
class BooleanInvalid(Invalid): ...
class UrlInvalid(Invalid): ...
class EmailInvalid(Invalid): ...
class FileInvalid(Invalid): ...
class DirInvalid(Invalid): ...
class PathInvalid(Invalid): ...
class LiteralInvalid(Invalid): ...
class LengthInvalid(Invalid): ...
class DatetimeInvalid(Invalid): ...
class DateInvalid(Invalid): ...
class InInvalid(Invalid): ...
class NotInInvalid(Invalid): ...
class ExactSequenceInvalid(Invalid): ...
class NotEnoughValid(Invalid): ...
class TooManyValid(Invalid): ...
